application: nz-twlee-demlookup
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /html
  static_dir: html

- url: /.*
  script: nzlookdemup.application

libraries:
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?dem/.*$
- ^(.*/)?nztmdem_1000x1000/.*$
- ^(.*/)?subset_dem/.*$
- ^(.*/)?.*\.csv$

