runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /elevation($|/.*)
  script: nzlookdemup.application
  
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static


libraries:
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?dem/.*$
- ^(.*/)?nztmdem_1000x1000/.*$
- ^(.*/)?subset_dem/.*$
- ^(.*/)?.*\.csv$

